#!/bin/bash

# Generated by https://ccstatusline.com/

#!/usr/bin/env bash
input=$(cat)

# Extract values
context_pct=$(echo "$input" | jq -r '.context_window.used_percentage // 0' | cut -d. -f1)
model_id=$(echo "$input" | jq -r '.model.id // ""')
model_display_name=$(echo "$input" | jq -r '.model.display_name // ""')
total_cost=$(printf "%.2f" "$(echo "$input" | jq -r '.cost.total_cost_usd // 0')")
tokens_in=$(echo "$input" | jq -r '.context_window.total_input_tokens // 0')
tokens_out=$(echo "$input" | jq -r '.context_window.total_output_tokens // 0')
duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // 0')
cache_pct=$(echo "$input" | jq -r '.context_window.current_usage | (.cache_read_input_tokens // 0) as $r | ((.cache_read_input_tokens // 0) + (.cache_creation_input_tokens // 0) + (.input_tokens // 0)) as $t | if $t > 0 then ($r * 100 / $t | floor) else 0 end')
api_ms=$(echo "$input" | jq -r '.cost.total_api_duration_ms // 0')
[ "$api_ms" -gt 0 ] && speed=$(( tokens_out * 1000 / api_ms )) || speed=0

# CWD
cwd_display=$(echo "$input" | jq -r '.cwd // ""')
cwd_display="${cwd_display/#$HOME/~}"
cwd_display=$(basename "$cwd_display")
[ "${#cwd_display}" -gt 40 ] && cwd_display="…${cwd_display: -39}"

# Colors
R='\033[0m'
C1='\033[38;2;60;56;54m'
C2='\033[38;2;146;131;116m'
C3='\033[38;2;235;219;178m'
C4='\033[38;2;136;136;180m'
C5='\033[38;2;180;180;180m'
C6='\033[38;2;184;187;38m'
C7='\033[38;2;215;153;33m'
C8='\033[38;2;251;73;52m'
C9='\033[38;2;177;98;134m'
C10='\033[38;2;140;194;74m'

number() {
  local n=$1
  if [ "$n" -ge 1000000 ]; then
    printf "%.1fM" "$(echo "scale=1; $n/1000000" | bc)"
  elif [ "$n" -ge 1000 ]; then
    printf "%.1fk" "$(echo "scale=1; $n/1000" | bc)"
  else
    printf "%d" "$n"
  fi
}

fmt_dur() {
  local ms=$1; local s=$(( ms/1000 )); local m=$(( s/60 )); local h=$(( m/60 ))
  m=$(( m%60 )); s=$(( s%60 ))
  printf "%d:%02d:%02d" $h $m $s
}

bar_cache() {
  local pct=${1:-0}
  local w=7
  local f=$(( (pct * w + 50) / 100 ))
  [ $f -gt $w ] && f=$w; [ $f -lt 0 ] && f=0
  local e=$(( w - f ))
  local c="${C8}"
  [ "$pct" -ge 50 ] && c="${C7}"
  [ "$pct" -ge 80 ] && c="${C6}"
  local s=""
  for ((i=0; i<f; i++)); do s+="█"; done
  printf "${c}%s${C1}" "$s"
  s=""
  for ((i=0; i<e; i++)); do s+="█"; done
  printf "%s${R}" "$s"
}

# Build output
out=""
out+="${C3}${cwd_display}${R}"
out+="${C1} | ${R}"
out+="${C3}${context_pct}%${R}"
out+="${C1} | ${R}"
out+="${C3}⚡ ${R}$(bar_cache "${cache_pct}")"
out+="${C1} | ${R}"
out+="${C3}↓$(number "${tokens_in}")${R}"
out+="${C1} | ${R}"
out+="${C3}↑$(number "${tokens_out}")${R}"
out+="${C1} | ${R}"
out+="${C3}${speed}t/s${R}"
out+="${C1} | ${R}"
out+="${C2}⏱ ${R}${C7}$(fmt_dur "${duration_ms}")${R}"
out+="${C1} | ${R}"
out+="${C3}\$${total_cost}${R}"
out+="${C1} | ${R}"
out+="${C2}★ ${R}${C9}${model_id}${R}${C2} ★${R}"

printf "%b" "$out"
